site_name: PC5132 Website

theme:
    name: "material"

    features:
        - navigation.tabs
        - search.suggest
        - search.share

    # 404 page
    static_templates:
        - 404.html

    # Necessary for search to work properly
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: material/telescope

    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode

extra_css:
    - stylesheets/style.css
    - stylesheets/solar_justice.css
    - stylesheets/quiz.css

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - md_in_html
    - pymdownx.tabbed:
          alternate_style: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home:
          - Index: stellar/graph.html
          - Welcome Screen: index.html
    - Preliminaries:
          - stellar/preliminaries/magnitude_scale.md
          - "The Hertzprung-Russell Diagram": stellar/preliminaries/hr_diagram.md
    - The Beginning:
          - "The Molecular Cloud": stellar/beginning/molecular_cloud.md
          - "The Protostar": stellar/beginning/protostar.md
          - "Herbig Ae/Be Stars": stellar/beginning/herbig-ae-be.md
          - "T-Tauri Stars": stellar/beginning/t-tauri.md
          - "Brown Dwarves": stellar/dwarves/brown_dwarf.md
    - Massive Track:
          - "Massive Stars": stellar/stars/massive_star.md
          - "Massive Star Death": stellar/others/massive_star_death.md
    - Low-Mass Track:
          - "Low-Mass Stars": stellar/stars/low_mass_star.md
          - stellar/giants/red_giant.md
          - Death:
                - stellar/dwarves/binary_white_dwarf.md
                - stellar/nova/nova.md
                - stellar/nova/type_1a_supernova.md
                - stellar/others/planetary_nebula.md
                - stellar/dwarves/white_dwarf.md
                - stellar/dwarves/black_dwarf.md
    - Games:
          - Home: stellar/games/index.md
          - Solar Justice: stellar/games/solarJustice/index.md

plugins:
    - mkdocs-jupyter
    - search

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/phytonics/PC5132-website

copyright: Copyright &copy; 2022 Phytonics
